[project]
name = "odoo-addons-oca-maintenance"
version = "18.0.20250729.0"
dependencies = [
    "odoo-addon-base_maintenance==18.0.*",
    "odoo-addon-maintenance_equipment_sequence==18.0.*",
    "odoo-addon-maintenance_project==18.0.*",
    "odoo-addon-maintenance_security==18.0.*",
    "odoo-addon-maintenance_timesheet==18.0.*",
    "odoo-addon-maintenance_timesheet_time_control==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
